### ISSUE TITLE
where to put .env file

### ISSUE THREAD

**Issue by pirpyn** [RasterCrow/Geo-Locator#7]
Hi, I'm trying to build the app, but I struggle with the .env file for firebase config key.

Where should i put it ?

Putting it in public/ raises an error, as the console reports that firebase lacks the projectId.

Changing the process.env.REACT... for the actual values works.

I'm not a web developer, so all that is new for me.

**Comment by pirpyn** [comment]
The .env file should be put at the root of the project i.e the root dir.

**Comment by RasterCrow** [comment]
> The .env file should be put at the root of the project i.e the root dir.

Correct 👍, feel free to contact me if you have other issues.
